name: jk_item_edit
version: '${project.version}'
main: jiekie.itemedit.ItemEditPlugin
api-version: '1.20'
authors: [Jiekie]
description: 아이템 설정 플러그인
commands:
  아이템:
    description: 아이템 설정 명령어
    usage: /아이템
    tab-completer: jiekie.itemedit.completer.ItemEditTabCompleter
    permission: jk.item_edit.command
    permission-message: ''